gcc -c -g -std=c11 -pedantic -Wall -Wextra ./center/source/main.c -o ./center/bin/main.o
gcc -c -g -std=c11 -pedantic -Wall -Wextra ./shared/source/arraylist.c -o ./center/bin/arraylist.o
gcc -c -g -std=c11 -pedantic -Wall -Wextra ./shared/source/json.c -o ./center/bin/json.o
gcc -c -g -std=c11 -pedantic -Wall -Wextra ./shared/source/sfuncs.c -o ./center/bin/sfuncs.o
gcc -g ./center/bin/main.o ./center/bin/arraylist.o ./center/bin/json.o ./center/bin/sfuncs.o -o ./center/bin/main.exe

# ./center/bin/main.exe
